---
- hosts: "{{ hosts_prompt }}"
  
  vars_prompt:
    - name: "hosts_prompt"
      prompt: "hostname or host group need to run with Playbook"
      private: no

  tasks:

    - name: Copy the Splunk Forwarder RPM to remote Servers.
      remote_user: ccox
      become: yes
      become_method: sudo
      copy:
         src: /Users/cameron.cox/Documents/Homelab/Ansible/admin/splunkforwarder-8.0.0-1357bef0a7f6-linux-2.6-x86_64.rpm
         dest: /home/ccox
         owner: ccox
         group: ccox
         mode: 0644
 
    - name: Install Splunk Forwarder RPM package on remote servers.
      remote_user: ccox
      become: yes
      become_method: sudo
      yum: state=present name={{ item }}
      with_items:
            - /home/ccox/splunkforwarder-8.0.0-1357bef0a7f6-linux-2.6-x86_64.rpm

    - name: Copy the Splunk Forwarder config from your centralized server to remote servers.
      remote_user: ccox
      become: yes
      become_method: sudo
      copy:
        src: /Users/cameron.cox/Documents/Homelab/Ansible/admin/outputs/
        dest: /opt/splunkforwarder/etc/system/
        directory_mode: yes
        owner: splunk
        group: splunk
        mode: 0600

    - name: Start Splunk forwarder service.
      remote_user: ccox
      become: yes
      become_method: sudo
      become_user: splunk
      shell:
        /opt/splunkforwarder/bin/splunk start --accept-license

    - name: Check Splunk forwarder service.
      remote_user: ccox
      become: yes
      become_method: sudo
      command:
        /opt/splunkforwarder/bin/splunk status
      register: service_splunk_status

    - name: Report Splunk forwarder Status.
      remote_user: ccox
      become: yes
      become_method: sudo
      debug:
         var: service_splunk_status.stdout_lines